# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
 branches:
  include:
   - master
 paths:
  include:
  - NotificationsClient/*

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/NotificationsClient.Android.sln'

- task: XamarinAndroid@1
  inputs:
    projectFile: '**/NotificationsClient.Android.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'

- task: AndroidSigning@3
  inputs:
    apksign: true
    zipalign: true
    apkFiles: '$(outputDirectory)/*.apk'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(outputDirectory)'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'ca-lbugnion-demo-test (6e69cf24-0859-4dec-84e2-695e2618e473)'
    scriptType: 'batch'
    scriptLocation: 'inlineScript'
    inlineScript: '"AzCopy\AzCopy.exe" copy "$(outputDirectory)\*.apk" "https://storageaccountlbnotb2a5.blob.core.windows.net/artifacts-android/$(Build.BuildNumber)/?sv=2019-02-02&ss=b&srt=sco&sp=rwlac&se=2020-04-24T16:19:48Z&st=2020-04-24T08:00:48Z&spr=https&sig=3Bgtoam07z5TKdfvtHIIHjWE2oM2ruhtgytkDRkPX3A%3D"'

- task: AzureFunction@1
  inputs:
    function: 'https://notificationsendpoint.azurewebsites.net/api/send'
    key: 'CfPYAamajXsaZQiFOk3CaLxFnDEKThXDnt86NWimMi5O2Gw8yeIK/Q=='
    method: 'POST'
    body: |
      {
      	"title": "Build completed for Android",
      	"body": "The build is ready: $(Build.BuildNumber)",
      	"channel": "NotificationsClient DevOps"
      }
    waitForCompletion: 'false'