# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
 branches:
  include:
   - master
 paths:
  include:
  - NotificationsClient/*

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/NotificationsClient.Android.sln'

- task: XamarinAndroid@1
  inputs:
    projectFile: '**/NotificationsClient.Android.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'

- task: AndroidSigning@3
  inputs:
    apksign: false
    zipalign: false
    apkFiles: '$(outputDirectory)/*.apk'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(outputDirectory)'

- task: AzureFileCopy@4
  inputs:
    SourcePath: '$(outputDirectory)'
    azureSubscription: 'ca-lbugnion-demo-test (6e69cf24-0859-4dec-84e2-695e2618e473)'
    Destination: 'AzureBlob'
    storage: 'storageaccountlbnotb2a5'
    ContainerName: 'BuildOutput'
    BlobPrefix: '$(Build.BuildNumber)'