### Send notification
POST {{function-url}}/api/send

{"title":"Error in web generation service","body":"Error with updated-cloud-avocate-profile.md: Index and length must refer to a location within the string. (Parameter 'length')","channel":"Web Generate ERRORS"}